ALTER TABLE "users"
ADD COLUMN "pomodoroWorkMin" INTEGER NOT NULL DEFAULT 25,
ADD COLUMN "pomodoroShortBreakMin" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN "pomodoroLongBreakMin" INTEGER NOT NULL DEFAULT 15;
